// Validating benchmarks:
// ***** BenchmarkRunner: Start   *****
// ***** Found 3 benchmark(s) in total *****
// ***** Building 1 exe(s) in Parallel: Start   *****
// start dotnet  restore /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 /p:Deterministic=true /p:Optimize=true in C:\Users\aruch\RiderProjects\WebApplication\StressTest\bin\Release\net7.0\e2401555-8d25-4eb9-a526-4d2c02f699bb
// command took 2.14 sec and exited with 0
// start dotnet  build -c Release --no-restore /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 /p:Deterministic=true /p:Optimize=true in C:\Users\aruch\RiderProjects\WebApplication\StressTest\bin\Release\net7.0\e2401555-8d25-4eb9-a526-4d2c02f699bb
// command took 5.03 sec and exited with 0
// ***** Done, took 00:00:07 (7.23 sec)   *****
// Found 3 benchmarks:
//   UserRegistrationBenchmark.Register10Users: DefaultJob
//   UserRegistrationBenchmark.Register50Users: DefaultJob
//   UserRegistrationBenchmark.Register100Users: DefaultJob

Setup power plan (GUID: 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c FriendlyName: Высокая производительность)
// **************************
// Benchmark: UserRegistrationBenchmark.Register10Users: DefaultJob
// *** Execute ***
// Launch: 1 / 1
// Execute: dotnet e2401555-8d25-4eb9-a526-4d2c02f699bb.dll --anonymousPipes 1976 1488 --benchmarkName StressTest.UserRegistrationBenchmark.Register10Users --job Default --benchmarkId 0 in C:\Users\aruch\RiderProjects\WebApplication\StressTest\bin\Release\net7.0\e2401555-8d25-4eb9-a526-4d2c02f699bb\bin\Release\net7.0
// BeforeAnythingElse

// Benchmark Process Environment Information:
// BenchmarkDotNet v0.13.8
// Runtime=.NET 7.0.11 (7.0.1123.42427), X64 RyuJIT AVX2
// GC=Concurrent Workstation
// HardwareIntrinsics=AVX2,AES,BMI1,BMI2,FMA,LZCNT,PCLMUL,POPCNT VectorSize=256
// Job: DefaultJob

OverheadJitting  1: 1 op, 361100.00 ns, 361.1000 us/op

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Net.Http.HttpRequestException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение. (localhost:5210)
 ---> System.Net.Sockets.SocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at StressTest.UserRegistrationBenchmark.RegisterUserAsync(Int32 userId) in C:\Users\aruch\RiderProjects\WebApplication\StressTest\UserRegistrationBenchmark.cs:line 67
   at StressTest.UserRegistrationBenchmark.RegisterUsersAsync(Int32 numberOfUsers) in C:\Users\aruch\RiderProjects\WebApplication\StressTest\UserRegistrationBenchmark.cs:line 45
   at StressTest.UserRegistrationBenchmark.Register10Users() in C:\Users\aruch\RiderProjects\WebApplication\StressTest\UserRegistrationBenchmark.cs:line 21
   at BenchmarkDotNet.Autogenerated.Runnable_0.<.ctor>b__3_3() in C:\Users\aruch\RiderProjects\WebApplication\StressTest\bin\Release\net7.0\e2401555-8d25-4eb9-a526-4d2c02f699bb\e2401555-8d25-4eb9-a526-4d2c02f699bb.notcs:line 197
   at BenchmarkDotNet.Autogenerated.Runnable_0.WorkloadActionNoUnroll(Int64 invokeCount) in C:\Users\aruch\RiderProjects\WebApplication\StressTest\bin\Release\net7.0\e2401555-8d25-4eb9-a526-4d2c02f699bb\e2401555-8d25-4eb9-a526-4d2c02f699bb.notcs:line 311
   at BenchmarkDotNet.Engines.Engine.RunIteration(IterationData data)
   at BenchmarkDotNet.Engines.EngineFactory.Jit(Engine engine, Int32 jitIndex, Int32 invokeCount, Int32 unrollFactor)
   at BenchmarkDotNet.Engines.EngineFactory.CreateReadyToRun(EngineParameters engineParameters)
   at BenchmarkDotNet.Autogenerated.Runnable_0.Run(IHost host, String benchmarkName) in C:\Users\aruch\RiderProjects\WebApplication\StressTest\bin\Release\net7.0\e2401555-8d25-4eb9-a526-4d2c02f699bb\e2401555-8d25-4eb9-a526-4d2c02f699bb.notcs:line 176
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in C:\Users\aruch\RiderProjects\WebApplication\StressTest\bin\Release\net7.0\e2401555-8d25-4eb9-a526-4d2c02f699bb\e2401555-8d25-4eb9-a526-4d2c02f699bb.notcs:line 57
// AfterAll
No Workload Results were obtained from the run.
// Benchmark Process 11992 has exited with code -1.

// ** Remained 2 (66,7 %) benchmark(s) to run. Estimated finish 2023-10-02 21:19 (0h 0m from now) **
Setup power plan (GUID: 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c FriendlyName: Высокая производительность)
// **************************
// Benchmark: UserRegistrationBenchmark.Register50Users: DefaultJob
// *** Execute ***
// Launch: 1 / 1
// Execute: dotnet e2401555-8d25-4eb9-a526-4d2c02f699bb.dll --anonymousPipes 1488 1044 --benchmarkName StressTest.UserRegistrationBenchmark.Register50Users --job Default --benchmarkId 1 in C:\Users\aruch\RiderProjects\WebApplication\StressTest\bin\Release\net7.0\e2401555-8d25-4eb9-a526-4d2c02f699bb\bin\Release\net7.0
// BeforeAnythingElse

// Benchmark Process Environment Information:
// BenchmarkDotNet v0.13.8
// Runtime=.NET 7.0.11 (7.0.1123.42427), X64 RyuJIT AVX2
// GC=Concurrent Workstation
// HardwareIntrinsics=AVX2,AES,BMI1,BMI2,FMA,LZCNT,PCLMUL,POPCNT VectorSize=256
// Job: DefaultJob

OverheadJitting  1: 1 op, 225300.00 ns, 225.3000 us/op

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Net.Http.HttpRequestException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение. (localhost:5210)
 ---> System.Net.Sockets.SocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at StressTest.UserRegistrationBenchmark.RegisterUserAsync(Int32 userId) in C:\Users\aruch\RiderProjects\WebApplication\StressTest\UserRegistrationBenchmark.cs:line 67
   at StressTest.UserRegistrationBenchmark.RegisterUsersAsync(Int32 numberOfUsers) in C:\Users\aruch\RiderProjects\WebApplication\StressTest\UserRegistrationBenchmark.cs:line 45
   at StressTest.UserRegistrationBenchmark.Register50Users() in C:\Users\aruch\RiderProjects\WebApplication\StressTest\UserRegistrationBenchmark.cs:line 27
   at BenchmarkDotNet.Autogenerated.Runnable_1.<.ctor>b__3_3() in C:\Users\aruch\RiderProjects\WebApplication\StressTest\bin\Release\net7.0\e2401555-8d25-4eb9-a526-4d2c02f699bb\e2401555-8d25-4eb9-a526-4d2c02f699bb.notcs:line 389
   at BenchmarkDotNet.Autogenerated.Runnable_1.WorkloadActionNoUnroll(Int64 invokeCount) in C:\Users\aruch\RiderProjects\WebApplication\StressTest\bin\Release\net7.0\e2401555-8d25-4eb9-a526-4d2c02f699bb\e2401555-8d25-4eb9-a526-4d2c02f699bb.notcs:line 503
   at BenchmarkDotNet.Engines.Engine.RunIteration(IterationData data)
   at BenchmarkDotNet.Engines.EngineFactory.Jit(Engine engine, Int32 jitIndex, Int32 invokeCount, Int32 unrollFactor)
   at BenchmarkDotNet.Engines.EngineFactory.CreateReadyToRun(EngineParameters engineParameters)
   at BenchmarkDotNet.Autogenerated.Runnable_1.Run(IHost host, String benchmarkName) in C:\Users\aruch\RiderProjects\WebApplication\StressTest\bin\Release\net7.0\e2401555-8d25-4eb9-a526-4d2c02f699bb\e2401555-8d25-4eb9-a526-4d2c02f699bb.notcs:line 368
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in C:\Users\aruch\RiderProjects\WebApplication\StressTest\bin\Release\net7.0\e2401555-8d25-4eb9-a526-4d2c02f699bb\e2401555-8d25-4eb9-a526-4d2c02f699bb.notcs:line 57
// AfterAll
No Workload Results were obtained from the run.
// Benchmark Process 8232 has exited with code -1.

// ** Remained 1 (33,3 %) benchmark(s) to run. Estimated finish 2023-10-02 21:19 (0h 0m from now) **
Setup power plan (GUID: 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c FriendlyName: Высокая производительность)
// **************************
// Benchmark: UserRegistrationBenchmark.Register100Users: DefaultJob
// *** Execute ***
// Launch: 1 / 1
// Execute: dotnet e2401555-8d25-4eb9-a526-4d2c02f699bb.dll --anonymousPipes 2004 2888 --benchmarkName StressTest.UserRegistrationBenchmark.Register100Users --job Default --benchmarkId 2 in C:\Users\aruch\RiderProjects\WebApplication\StressTest\bin\Release\net7.0\e2401555-8d25-4eb9-a526-4d2c02f699bb\bin\Release\net7.0
// BeforeAnythingElse

// Benchmark Process Environment Information:
// BenchmarkDotNet v0.13.8
// Runtime=.NET 7.0.11 (7.0.1123.42427), X64 RyuJIT AVX2
// GC=Concurrent Workstation
// HardwareIntrinsics=AVX2,AES,BMI1,BMI2,FMA,LZCNT,PCLMUL,POPCNT VectorSize=256
// Job: DefaultJob

OverheadJitting  1: 1 op, 217500.00 ns, 217.5000 us/op

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Net.Http.HttpRequestException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение. (localhost:5210)
 ---> System.Net.Sockets.SocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at StressTest.UserRegistrationBenchmark.RegisterUserAsync(Int32 userId) in C:\Users\aruch\RiderProjects\WebApplication\StressTest\UserRegistrationBenchmark.cs:line 67
   at StressTest.UserRegistrationBenchmark.RegisterUsersAsync(Int32 numberOfUsers) in C:\Users\aruch\RiderProjects\WebApplication\StressTest\UserRegistrationBenchmark.cs:line 45
   at StressTest.UserRegistrationBenchmark.Register100Users() in C:\Users\aruch\RiderProjects\WebApplication\StressTest\UserRegistrationBenchmark.cs:line 33
   at BenchmarkDotNet.Autogenerated.Runnable_2.<.ctor>b__3_3() in C:\Users\aruch\RiderProjects\WebApplication\StressTest\bin\Release\net7.0\e2401555-8d25-4eb9-a526-4d2c02f699bb\e2401555-8d25-4eb9-a526-4d2c02f699bb.notcs:line 581
   at BenchmarkDotNet.Autogenerated.Runnable_2.WorkloadActionNoUnroll(Int64 invokeCount) in C:\Users\aruch\RiderProjects\WebApplication\StressTest\bin\Release\net7.0\e2401555-8d25-4eb9-a526-4d2c02f699bb\e2401555-8d25-4eb9-a526-4d2c02f699bb.notcs:line 695
   at BenchmarkDotNet.Engines.Engine.RunIteration(IterationData data)
   at BenchmarkDotNet.Engines.EngineFactory.Jit(Engine engine, Int32 jitIndex, Int32 invokeCount, Int32 unrollFactor)
   at BenchmarkDotNet.Engines.EngineFactory.CreateReadyToRun(EngineParameters engineParameters)
   at BenchmarkDotNet.Autogenerated.Runnable_2.Run(IHost host, String benchmarkName) in C:\Users\aruch\RiderProjects\WebApplication\StressTest\bin\Release\net7.0\e2401555-8d25-4eb9-a526-4d2c02f699bb\e2401555-8d25-4eb9-a526-4d2c02f699bb.notcs:line 560
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in C:\Users\aruch\RiderProjects\WebApplication\StressTest\bin\Release\net7.0\e2401555-8d25-4eb9-a526-4d2c02f699bb\e2401555-8d25-4eb9-a526-4d2c02f699bb.notcs:line 57
// AfterAll
No Workload Results were obtained from the run.
// Benchmark Process 9844 has exited with code -1.

// ** Remained 0 (0,0 %) benchmark(s) to run. Estimated finish 2023-10-02 21:19 (0h 0m from now) **
Successfully reverted power plan (GUID: 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c FriendlyName: Высокая производительность)
// ***** BenchmarkRunner: Finish  *****

// * Export *
  BenchmarkDotNet.Artifacts\results\StressTest.UserRegistrationBenchmark-report.csv
  BenchmarkDotNet.Artifacts\results\StressTest.UserRegistrationBenchmark-report-github.md
  BenchmarkDotNet.Artifacts\results\StressTest.UserRegistrationBenchmark-report.html

// * Detailed results *
UserRegistrationBenchmark.Register10Users: DefaultJob
Runtime = .NET 7.0.11 (7.0.1123.42427), X64 RyuJIT AVX2; GC = Concurrent Workstation
There are not any results runs

UserRegistrationBenchmark.Register50Users: DefaultJob
Runtime = .NET 7.0.11 (7.0.1123.42427), X64 RyuJIT AVX2; GC = Concurrent Workstation
There are not any results runs

UserRegistrationBenchmark.Register100Users: DefaultJob
Runtime = .NET 7.0.11 (7.0.1123.42427), X64 RyuJIT AVX2; GC = Concurrent Workstation
There are not any results runs

// * Summary *

BenchmarkDotNet v0.13.8, Windows 10 (10.0.19045.3448/22H2/2022Update)
AMD Ryzen 5 5500U with Radeon Graphics, 1 CPU, 12 logical and 6 physical cores
.NET SDK 7.0.401
  [Host]     : .NET 7.0.11 (7.0.1123.42427), X64 RyuJIT AVX2
  DefaultJob : .NET 7.0.11 (7.0.1123.42427), X64 RyuJIT AVX2


| Method           | Mean | Error |
|----------------- |-----:|------:|
| Register10Users  |   NA |    NA |
| Register50Users  |   NA |    NA |
| Register100Users |   NA |    NA |

Benchmarks with issues:
  UserRegistrationBenchmark.Register10Users: DefaultJob
  UserRegistrationBenchmark.Register50Users: DefaultJob
  UserRegistrationBenchmark.Register100Users: DefaultJob

// * Warnings *
Environment
  Summary -> Detected error exit code from one of the benchmarks. It might be caused by following antivirus software:
        - Windows Defender (windowsdefender://)
Use InProcessEmitToolchain or InProcessNoEmitToolchain to avoid new process creation.


// * Legends *
  Mean  : Arithmetic mean of all measurements
  Error : Half of 99.9% confidence interval
  1 ns  : 1 Nanosecond (0.000000001 sec)

// * Diagnostic Output - MemoryDiagnoser *


// ***** BenchmarkRunner: End *****
Run time: 00:00:13 (13.28 sec), executed benchmarks: 3

Global total time: 00:00:20 (20.56 sec), executed benchmarks: 3
// * Artifacts cleanup *
Artifacts cleanup is finished
